on:
  release:
    types: [created]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: |
          VERSION=$(node -p -e "require('./package.json').version")
          git config --global user.email "mohannad.otaibi@gmail.com"
          git config --global user.name "Mohannad Otaibi"
          npm version $VERSION
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
  release:
    needs: publish-npm
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get version number
        id: version
        run: echo "::set-output name=version::$(node -p -e "require('./package.json').version")"
      - name: Get the latest tag
        id: get_tag
        run: echo ::set-output name=TAG::$(git describe --tags $(git rev-list --tags --max-count=1))
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          body: |
            Changes in this Release
            - $(git log --pretty=format:'%s' -n 1)
          draft: false
          prerelease: false