on:
  release:
    types: [created]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  release:
    needs: publish-npm
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get version number
        id: version
        run: echo "::set-output name=version::$(node -p -e "require('./package.json').version")"
      - name: Get the latest tag
        id: get_tag
        run: echo ::set-output name=TAG::$(git describe --tags $(git rev-list --tags --max-count=1))
      - name: Set release notes
        id: set_release_notes
        run: |
          #!/bin/bash
          release_notes=$(git log --pretty=format:'%s' -n 1)
          echo "RELEASE_NOTES=$release_notes" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          body: |
            Changes in this Release
            - ${{ env.RELEASE_NOTES }}
          draft: false
          prerelease: false